version: '3.4'

services:
  elasticsearch-v5:
    build:
      context: .
      dockerfile: elasticsearch-v5.dockerfile
    image: vulcanizer-elasticsearch:v5
    container_name: vulcanizer-elasticsearch-v5
    environment:
      - cluster.name=vulcanizer-elasticsearch-v5
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 49200:9200
    healthcheck:
      start_period: 10s
      interval: 60s
      retries: 3
      test: ["CMD", "curl", "--fail", "http://localhost:49200/_cat/health"]
