# http://docs.travis-ci.com/user/languages/go/
language: go

go:
 - "1.10.x"
 - "1.11.x"

os:
    - linux

env:
  - YOUR_VAR=your_value

install: true

script: script/test

notifications:
    email: false
