# http://docs.travis-ci.com/user/languages/go/
language: go

go:
    - "1.10.x"
    - "1.11.x"

os:
    - linux

install: true

before_script:
    curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.11.2

script: script/test

notifications:
    email: false
