# http://docs.travis-ci.com/user/languages/go/
language: go

matrix:
  include:
  - go: 1.13.x
  - go: 1.12.x
    env: GO111MODULE=on
  - go: 1.11.x
    env: GO111MODULE=on

services:
    - docker
os:
    - linux

install: true

before_script:
    curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.18.0

script: script/integration-test

notifications:
    email: false
