[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/parnurzeal/gorequest"

[[constraint]]
  branch = "master"
  name = "github.com/tidwall/gjson"

[[constraint]]
  branch = "master"
  name = "github.com/jeremywohl/flatten"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/viper"
