version: '3'

services:
  elasticsearch-v7:
    build:
      context: .
      dockerfile: elasticsearch.dockerfile
    image: vulcanizer-elasticsearch:v7
    container_name: vulcanizer-elasticsearch-v7
    environment:
      - cluster.name=vulcanizer-elasticsearch-v7
      - node.name=vulcanizer-elasticsearch-v7
      - bootstrap.memory_lock=true
      - "path.repo=/backups"
      - "discovery.seed_hosts=vulcanizer-elasticsearch-v7,vulcanizer-elasticsearch-v7-2"
      - "cluster.initial_master_nodes=vulcanizer-elasticsearch-v7,vulcanizer-elasticsearch-v7-2"
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 49200:9200
    networks:
      - vulcanizer-esnet
    volumes:
      - vulcanizer-backup-volume:/backups

  elasticsearch-v7-2:
    build:
      context: .
      dockerfile: elasticsearch-v7.dockerfile
    image: vulcanizer-elasticsearch:v7
    depends_on:
      - "elasticsearch-v7"
    container_name: vulcanizer-elasticsearch-v7-2
    environment:
      - cluster.name=vulcanizer-elasticsearch-v7
      - bootstrap.memory_lock=true
      - node.name=vulcanizer-elasticsearch-v7-2
      - "path.repo=/backups"
      - "discovery.seed_hosts=vulcanizer-elasticsearch-v7,vulcanizer-elasticsearch-v7-2"
      - "cluster.initial_master_nodes=vulcanizer-elasticsearch-v7,vulcanizer-elasticsearch-v7-2"
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
      - vulcanizer-esnet
    volumes:
      - vulcanizer-backup-volume:/backups

networks:
  vulcanizer-esnet:

volumes:
  vulcanizer-backup-volume:
