---
name: Vulcanizer CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18.x']
    name: Vulcanizer tests against go version ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - name: Run tests
      run: |
        curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.46.2
        sudo cp ./bin/golangci-lint $GOROOT/bin/
        sudo sysctl -w vm.max_map_count=262144
        script/integration-test
