---
name: Vulcanizer CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.11.x', '1.12.x', '1.13.x' ]
    name: Vulcanizer tests against go version ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: Run tests
      run: |
        curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOROOT/bin v1.18.0
        sudo sysctl -w vm.max_map_count=262144
        script/integration-test
