---
name: Vulcanizer CI
on: [push, pull_request]
permissions: 
  contents: read
  actions: read
  checks: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17.x', '1.22.x' ]
    name: Vulcanizer tests against go version ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - name: Run tests
      run: |
        sudo sysctl -w vm.max_map_count=262144
        script/integration-test
